import type { MediaItem } from './types'

/**
 * Media coverage — shown as an interactive timeline (rendered newest first).
 * `kind` drives the icon: video / article / interview / post.
 * `image` points into public/images/ (downloaded press thumbnails).
 */
export const media: MediaItem[] = [
  {
    id: 'rthk-2026',
    date: '2026-04-28',
    outlet: 'RTHK 香港電台',
    title: {
      en: 'Hong Kong United: emergency drones tackle “rescue blind spots” in the mountains',
      zhHant: '《凝聚香港》：無人機滲透・山野中急救，助解決「救援盲點」',
      zhHans: '《凝聚香港》：无人机渗透・山野中急救，助解决「救援盲点」',
    },
    summary: {
      en: 'RTHK’s Hong Kong United features AeroRelief: the casualty taps an SMS link, the AI dispatch gets precise positioning, and the drone delivers supplies where ambulances cannot reach. Jimmy Wu explains the system in-studio with the prototype.',
      zhHant: '港台《凝聚香港》專題介紹 AeroRelief：求救者點擊短訊連結，AI 調度即時獲取精準定位，無人機把物資送到救護車難以抵達之處。胡駿銘於錄影廠講解系統運作。',
      zhHans: '港台《凝聚香港》专题介绍 AeroRelief：求救者点击短信链接，AI 调度即时获取精准定位，无人机把物资送到救护车难以抵达之处。胡骏铭于录影厂讲解系统运作。',
    },
    url: 'https://www.rthk.hk/tv/dtt31/programme/hkunited/episode/1089064',
    kind: 'video',
    major: true,
    logo: '/logos/rthk.png',
    image: '/images/media-rthk-1.jpg',
  },
  {
    id: 'sciencenet-2026',
    date: '2026-04-02',
    outlet: 'ScienceNet 科学网',
    title: {
      en: 'HKUST wins 62 awards at Geneva — AeroRelief among showcased Gold Medal projects',
      zhHant: '科大日內瓦發明展奪 62 獎，AeroRelief 為金獎展示項目之一',
      zhHans: '科大日内瓦发明展夺 62 奖，AeroRelief 为金奖展示项目之一',
    },
    summary: {
      en: 'Coverage of HKUST’s record 62 awards at the 51st International Exhibition of Inventions Geneva, showcasing AeroRelief as a Gold Medal with Congratulations of the Jury project.',
      zhHant: '報道科大在第 51 屆日內瓦國際發明展破紀錄奪得 62 個獎項，AeroRelief 為評審團嘉許金獎展示項目。',
      zhHans: '报道科大在第 51 届日内瓦国际发明展破纪录夺得 62 个奖项，AeroRelief 为评审团嘉许金奖展示项目。',
    },
    url: 'https://news.sciencenet.cn/htmlnews/2026/4/562450.shtm',
    kind: 'article',
    logo: '/logos/sciencenet.jpg',
    image: '/images/media-geneva-seng-3.jpg',
  },
  {
    id: 'am730-geneva-2026',
    date: '2026-03-31',
    outlet: 'am730',
    title: {
      en: 'HKUST wins record 62 Geneva awards — AeroRelief’s 10 km automated rescue route explained',
      zhHant: '科大日內瓦發明展破紀錄奪 62 獎　胡駿銘講解 AeroRelief 全自動救援航線',
      zhHans: '科大日内瓦发明展破纪录夺 62 奖　胡骏铭讲解 AeroRelief 全自动救援航线',
    },
    summary: {
      en: 'am730 interviews Jimmy Wu at the Geneva award showcase: the 25 kg-class drone gets the caller’s position via SMS, plans a fully automated 10 km route on Hong Kong’s 3D map, and delivers ~5 kg of medical supplies such as AEDs and adrenaline pens to Sai Kung’s country parks.',
      zhHant: 'am730 於日內瓦獲獎展示會訪問胡駿銘：25 公斤級無人機透過短訊取得報警者定位，結合香港三維地圖規劃全自動 10 公里航線，載約 5 公斤急救物資（AED、腎上腺素筆）飛往西貢郊野。',
      zhHans: 'am730 于日内瓦获奖展示会访问胡骏铭：25 公斤级无人机通过短信取得报警者定位，结合香港三维地图规划全自动 10 公里航线，载约 5 公斤急救物资（AED、肾上腺素笔）飞往西贡郊野。',
    },
    url: 'https://www.am730.com.hk/article/1022644',
    kind: 'interview',
    major: true,
    logo: '/logos/am730.png',
    image: '/images/media-am730-sandbox-1.jpg',
  },
  {
    id: 'geneva-news-2026',
    date: '2026-03-15',
    outlet: 'HKUST News',
    title: {
      en: 'HKUST innovations shine at the International Exhibition of Inventions Geneva',
      zhHant: '科大於日內瓦發明展創紀錄奪 62 獎',
      zhHans: '科大于日内瓦发明展创纪录夺 62 奖',
    },
    summary: {
      en: 'AeroRelief: Autonomous UAV First-Responder System receives a Gold Medal with Congratulations of the Jury at the 51st International Exhibition of Inventions Geneva.',
      zhHant: 'AeroRelief 自主無人機急救系統於第 51 屆日內瓦國際發明展獲頒評審團嘉許金獎。',
      zhHans: 'AeroRelief 自主无人机急救系统于第 51 届日内瓦国际发明展获颁评审团嘉许金奖。',
    },
    url: 'https://hkust.edu.hk/news/hkust-innovations-shine-international-exhibition-inventions-geneva',
    kind: 'article',
    logo: '/logos/geneva.png',
    image: '/images/media-geneva-seng-1.jpg',
  },
  {
    id: 'wenweipo-lae-2026',
    date: '2026-03-02',
    outlet: 'Wen Wei Po 文匯報',
    title: {
      en: 'Flying in dense cities — two key technologies',
      zhHant: '密集城市飛行　關鍵兩大技術',
      zhHans: '密集城市飞行　关键两大技术',
    },
    summary: {
      en: 'Wen Wei Po on urban drone operations, citing AeroRelief’s AED delivery, sandbox approval and collaboration talks with the HK Heart Resuscitation Association, police and fire services.',
      zhHant: '文匯報報道城市無人機運作，提及 AeroRelief 的 AED 運送、沙盒批核，以及與香港心臟復甦協會、東九龍警署和消防署的合作探討。',
      zhHans: '文汇报报道城市无人机运作，提及 AeroRelief 的 AED 运送、沙盒批核，以及与香港心脏复苏协会、东九龙警署和消防署的合作探讨。',
    },
    url: 'https://www.wenweipo.com/a/202603/02/AP69a49ee3e4b04d7d56d5ed81.html',
    kind: 'article',
    logo: '/logos/wenweipo.png',
    image: '/images/media-wands-1.jpg',
  },
  {
    id: 'belt-road-2026',
    date: '2026-01-05',
    outlet: 'HKUST Knowledge Transfer',
    title: {
      en: 'Belt and Road low-altitude economy delegation explores innovation at HKUST',
      zhHant: '「一帶一路」低空經濟代表團到訪科大　胡駿銘演示救援無人機',
      zhHans: '「一带一路」低空经济代表团到访科大　胡骏铭演示救援无人机',
    },
    summary: {
      en: 'The Low Altitude Economy Research Center hosts a Belt and Road delegation led by Silk Road Cities Alliance founder Song Ronghua; Jimmy Wu demonstrates the team’s custom multirotor rescue drone and AED payload.',
      zhHant: '低空經濟研究中心接待由絲路城市聯盟創始人宋榮華率領的「一帶一路」代表團，胡駿銘現場演示團隊自研的多旋翼救援無人機及 AED 運送艙。',
      zhHans: '低空经济研究中心接待由丝路城市联盟创始人宋荣华率领的「一带一路」代表团，胡骏铭现场演示团队自研的多旋翼救援无人机及 AED 运送舱。',
    },
    url: 'https://okt.hkust.edu.hk/news/belt-and-road-low-altitude-economy-delegation-explores-innovation-hkust',
    kind: 'article',
    logo: '/logos/hkust.svg',
    image: '/images/media-belt-road-1.jpg',
  },
  {
    id: 'tvbs-2025',
    date: '2025-11-24',
    outlet: 'TVBS News',
    title: {
      en: 'AI aerial rescue rewrites the golden window — saving lives where mountains have no signal',
      zhHant: '山區無訊號也能救命　AI 空中救援改寫求生黃金期',
      zhHans: '山区无讯号也能救命　AI 空中救援改写求生黄金期',
    },
    summary: {
      en: 'TVBS News feature on how AeroRelief’s AI dispatch platform and drone delivery change emergency rescue in remote terrain.',
      zhHant: 'TVBS 新聞專題：AeroRelief 的 AI 調度平台與無人機運送如何改寫偏遠地區的緊急救援。',
      zhHans: 'TVBS 新闻专题：AeroRelief 的 AI 调度平台与无人机运送如何改写偏远地区的紧急救援。',
    },
    url: 'https://today.line.me/tw/v3/article/aG5BDPp',
    kind: 'video',
    major: true,
    logo: '/logos/tvbs.png',
    image: '/images/featured-tvbs.jpg',
  },
  {
    id: 'hkust-ais-2025',
    date: '2025-11-18',
    outlet: 'HKUST AIS',
    title: {
      en: 'ISD UG graduates showcase emergency delivery drone on CNN’s Tech for Good',
      zhHant: 'ISD 畢業生登上 CNN《Tech for Good》展示急救無人機',
      zhHans: 'ISD 毕业生登上 CNN《Tech for Good》展示急救无人机',
    },
    summary: {
      en: 'HKUST Academy of Interdisciplinary Studies covers the CNN feature and the story of the AeroRelief team.',
      zhHant: '科大跨學科學院報道 CNN 專題及 AeroRelief 團隊的故事。',
      zhHans: '科大跨学科学院报道 CNN 专题及 AeroRelief 团队的故事。',
    },
    url: 'https://ais.hkust.edu.hk/whats-happening/news/isd-ug-graduates-showcase-innovative-emergency-delivery-drone-system-cnns-tech',
    kind: 'article',
    logo: '/logos/hkust.svg',
    image: '/images/aerorelief-3.jpg',
  },
  {
    id: 'congregation-2025',
    date: '2025-11-15',
    outlet: 'HKUST Congregation',
    title: {
      en: 'Graduate representative address — WU Chun-Ming, BSc in Integrative Systems and Design',
      zhHant: '畢業生代表致辭——胡駿銘　綜合系統與設計理學士',
      zhHans: '毕业生代表致辞——胡骏铭　综合系统与设计理学士',
    },
    summary: {
      en: 'Jimmy Wu is selected to speak on behalf of School of Engineering graduates at the 2025 Congregation, reflecting on failed 3D prints and burned ESP32s — and urging the class to carry the ISD spirit of innovation and empathy forward.',
      zhHant: '胡駿銘獲選於 2025 年畢業典禮代表工學院畢業生致辭，回顧失敗的 3D 打印與燒毀的 ESP32，寄語同屆秉持創新與同理心的 ISD 精神前行。',
      zhHans: '胡骏铭获选于 2025 年毕业典礼代表工学院毕业生致辞，回顾失败的 3D 打印与烧毁的 ESP32，寄语同届秉持创新与同理心的 ISD 精神前行。',
    },
    url: 'https://booklet.congregation.ust.hk/2025/cbook_book4/24/',
    kind: 'article',
    logo: '/logos/hkust.svg',
  },
  {
    id: 'cnn-tech-for-good-2025',
    date: '2025-10-27',
    outlet: 'CNN',
    title: {
      en: 'Tech for Good: this drone could one day help save lives in remote areas',
      zhHant: 'CNN《Tech for Good》：這部無人機有朝一日可在偏遠地區拯救生命',
      zhHans: 'CNN《Tech for Good》：这部无人机有朝一日可在偏远地区拯救生命',
    },
    summary: {
      en: 'Kristie Lu Stout visits HKUST to feature AeroRelief — young innovators redefining rescue missions with robotics.',
      zhHant: 'Kristie Lu Stout 到訪科大，專題報道 AeroRelief——年輕創新者以機械人技術重新定義救援任務。',
      zhHans: 'Kristie Lu Stout 到访科大，专题报道 AeroRelief——年轻创新者以机器人技术重新定义救援任务。',
    },
    url: 'https://www.cnn.com/2025/10/27/world/video/aerorelief-emergency-drone-hong-kong-tech-for-good-hnk-spc',
    kind: 'video',
    major: true,
    logo: '/logos/cnn.svg',
    image: '/images/cnn-tech-for-good.jpg',
  },
  {
    id: 'asmpt-2025',
    date: '2025-07-15',
    outlet: 'HKUST SENG',
    title: {
      en: 'AeroRelief wins Gold Award at the ASMPT Technology Award 2025',
      zhHant: 'AeroRelief 榮獲 2025 年 ASMPT 科技獎金獎',
      zhHans: 'AeroRelief 荣获 2025 年 ASMPT 科技奖金奖',
    },
    summary: {
      en: 'Jimmy Wu and his ISD teammates win the Gold Award — with a HK$100,000 Young Engineer Scholarship — for “AeroRelief: Drone as First Responder in Time-Critical Emergency Mission”.',
      zhHant: '胡駿銘與 ISD 隊友憑「AeroRelief：分秒必爭的無人機急救先鋒」奪得金獎，並獲頒十萬港元青年工程師獎學金。',
      zhHans: '胡骏铭与 ISD 队友凭「AeroRelief：分秒必争的无人机急救先锋」夺得金奖，并获颁十万港元青年工程师奖学金。',
    },
    url: 'https://seng.hkust.edu.hk/zh-hant/news/20250715/two-undergraduate-teams-won-gold-and-outstanding-awards-asmpt-technology-award-2025',
    kind: 'article',
    logo: '/logos/asmpt.png',
    image: '/images/media-asmpt-1.jpg',
  },
  {
    id: 'hkust-lae-2025',
    date: '2025-04-07',
    outlet: 'HKUST News',
    title: {
      en: 'The sky’s not the limit — Hong Kong’s low-altitude economy takes wing',
      zhHant: '飛越無限：低空經濟蓄翼待飛',
      zhHans: '飞越无限：低空经济蓄翼待飞',
    },
    summary: {
      en: 'HKUST feature on the Low Altitude Economy Research Center, highlighting AeroRelief’s AI-driven emergency rescue delivery system.',
      zhHant: '科大低空經濟研究中心專題，重點介紹 AeroRelief 人工智能緊急救援運送系統。',
      zhHans: '科大低空经济研究中心专题，重点介绍 AeroRelief 人工智能紧急救援运送系统。',
    },
    url: 'https://hkust.edu.hk/zh-hans/news/skys-not-limit-its-whole-new-world',
    kind: 'article',
    logo: '/logos/hkust.svg',
    image: '/images/lae-1.jpg',
  },
  {
    id: 'am730-2025',
    date: '2025-03-21',
    outlet: 'am730',
    title: {
      en: 'Hong Kong’s low-altitude economy takes off — 38 pilot projects including drone-delivered AEDs',
      zhHant: '港低空經濟起飛　首批 38 試點　無人機送藥送餐送 AED 機',
      zhHans: '港低空经济起飞　首批 38 试点　无人机送药送餐送 AED 机',
    },
    summary: {
      en: 'am730 covers the first Regulatory Sandbox batch, detailing AeroRelief’s 5–6 kg payload, 10 km range and partnership with the HK Resuscitation Society and China Unicom.',
      zhHant: 'am730 報道首批監管沙盒項目，詳述 AeroRelief 5–6 公斤載重、10 公里航程，以及與香港復甦學會、中國聯通的合作。',
      zhHans: 'am730 报道首批监管沙盒项目，详述 AeroRelief 5–6 公斤载重、10 公里航程，以及与香港复苏学会、中国联通的合作。',
    },
    url: 'https://www.am730.com.hk/article/543513',
    kind: 'article',
    major: true,
    logo: '/logos/am730.png',
  },
  {
    id: 'seng-sandbox-2025',
    date: '2025-03-20',
    outlet: 'HKUST SENG',
    title: {
      en: 'Government launches LAE Regulatory Sandbox pilot projects at HKUST',
      zhHant: '政府於科大啓動「監管沙盒」試點項目　促進低空經濟和創新產業發展',
      zhHans: '政府于科大启动「监管沙盒」试点项目　促进低空经济和创新产业发展',
    },
    summary: {
      en: 'AeroRelief is selected as one of the first pilot projects of the HKSAR Government’s Low-Altitude Economy Regulatory Sandbox; Jimmy Wu presents the system to Chief Executive John Lee at the launch.',
      zhHant: 'AeroRelief 入選香港特區政府低空經濟「監管沙盒」首批試點項目，胡駿銘於啟動禮向行政長官李家超介紹系統。',
      zhHans: 'AeroRelief 入选香港特区政府低空经济「监管沙盒」首批试点项目，胡骏铭于启动礼向行政长官李家超介绍系统。',
    },
    url: 'https://seng.hkust.edu.hk/zh-hant/news/20250320/government-launches-regulatory-sandbox-pilot-projects-hkust-foster-low-altitude-economy-and-innovative-industry-development',
    kind: 'article',
    major: true,    logo: '/logos/hkust.svg',
    image: '/images/media-sandbox-1.jpg',
  },
  {
    id: 'unwire-ig-2025',
    date: '2025-01-19',
    outlet: 'unwire.hk',
    title: {
      en: 'Low-altitude economy — can it work in Hong Kong? Drones beyond food delivery',
      zhHant: '低空經濟　香港可行嗎？無人機除咗送外賣，醫療急救都非常有用',
      zhHans: '低空经济　香港可行吗？无人机除了送外卖，医疗急救都非常有用',
    },
    summary: {
      en: 'unwire.hk’s explainer reel on Hong Kong’s low-altitude economy covers HKUST’s new Low Altitude Economy Research Center and its drone emergency-rescue work — the research behind AeroRelief — plus the regulatory sandbox application.',
      zhHant: 'unwire.hk 短片講解香港低空經濟，介紹科大新成立的低空經濟研究中心及其無人機緊急救援研究（AeroRelief 背後的研究），以及「監管沙盒」申請。',
      zhHans: 'unwire.hk 短片讲解香港低空经济，介绍科大新成立的低空经济研究中心及其无人机紧急救援研究（AeroRelief 背后的研究），以及「监管沙盒」申请。',
    },
    url: 'https://www.instagram.com/reel/DFCLdvsNS3i/',
    kind: 'post',
    major: true,
    logo: '/logos/unwire.png',
    image: '/images/media-ig-reel-1.jpg',
  },
  {
    id: 'mingpao-2025',
    date: '2025-01-16',
    outlet: 'Ming Pao 明報',
    title: {
      en: 'HKUST establishes Low-Altitude Economy Research Centre, hopes for relaxed flight rules',
      zhHant: '科大成立低空經濟研究中心　盼寬飛行法規',
      zhHans: '科大成立低空经济研究中心　盼宽飞行法规',
    },
    summary: {
      en: 'Ming Pao reports on the Centre’s seven drone projects; Jimmy Wu demonstrates the AED delivery live — a drone circling campus tracked in real time — and says he hopes drones can save lives in cardiac arrest, heatstroke and severe allergy cases.',
      zhHant: '明報報道中心七個無人機項目；胡駿銘現場示範 AED 運送——實時追蹤無人機飛繞校園——並表示盼無人機能在心臟驟停、中暑、嚴重過敏等緊急情況下挽救生命。',
      zhHans: '明报报道中心七个无人机项目；胡骏铭现场示范 AED 运送——实时追踪无人机飞绕校园——并表示盼无人机能在心脏骤停、中暑、严重过敏等紧急情况下挽救生命。',
    },
    url: 'https://resources.mpep.com.hk/news/8/55373',
    kind: 'article',
    major: true,
    logo: '/logos/mingpao.png',
    image: '/images/media-mpep-1.jpg',
  },
  {
    id: 'wenweipo-2025',
    date: '2025-01-16',
    outlet: 'Wen Wei Po 文匯報',
    title: {
      en: 'Drone rescue — Jimmy Wu demonstrates AeroRelief at the LAERC launch',
      zhHant: '無人機救援——胡駿銘於低空經濟研究中心啟動禮展示 AeroRelief',
      zhHans: '无人机救援——胡骏铭于低空经济研究中心启动礼展示 AeroRelief',
    },
    summary: {
      en: 'Wen Wei Po covers the live demo: a hiker collapses, a passerby calls for help, an SMS link shares the location, and the drone delivers an AED before rescuers arrive.',
      zhHant: '文匯報報道現場示範：行山者倒地，途人致電求助，手機短訊連結傳送位置，無人機起飛送遞 AED，爭取救援時間。',
      zhHans: '文汇报报道现场示范：行山者倒地，途人致电求助，手机短信链接传送位置，无人机起飞送递 AED，争取救援时间。',
    },
    url: 'https://www.wenweipo.com/a/202501/16/AP678818f4e4b0ebdedfc24e59.html',
    kind: 'article',
    logo: '/logos/wenweipo.png',
    image: '/images/media-lae-center-2.jpg',
  },
  {
    id: 'tvb-2025',
    date: '2025-01-15',
    outlet: 'TVB News 無綫新聞',
    title: {
      en: 'HKUST team develops drone rescue system for hiking rescue and emergency supply delivery',
      zhHant: '科大團隊研無人機救援系統　冀應用於行山救援及運送緊急物資',
      zhHans: '科大团队研无人机救援系统　冀应用于行山救援及运送紧急物资',
    },
    summary: {
      en: 'TVB News reports on the AeroRelief team’s AI-piloted drone that navigates mountains autonomously to locate stranded hikers and deliver supplies, quoting Jimmy Wu on how the system plans routes and drops supplies.',
      zhHant: '無綫新聞報道 AeroRelief 團隊以 AI 自動駕駛無人機穿梭山嶺，定位被困行山人士並運送救援物資，並引述胡駿銘講解系統如何規劃航線及投放物資。',
      zhHans: '无线新闻报道 AeroRelief 团队以 AI 自动驾驶无人机穿梭山岭，定位被困行山人士并运送救援物资，并引述胡骏铭讲解系统如何规划航线及投放物资。',
    },
    url: 'https://news.tvb.com/tc/812541-%E7%A7%91%E5%A4%A7%E5%9C%98%E9%9A%8A%E7%A0%94%E7%84%A1%E4%BA%BA%E6%A9%9F%E6%95%91%E6%8F%B4%E7%B3%BB%E7%B5%B1%E5%86%80%E6%87%89%E7%94%A8%E6%96%BC%E8%A1%8C%E5%B1%B1%E6%95%91%E6%8F%B4%E5%8F%8A%E9%81%8B%E9%80%81%E7%B7%8A%E6%80%A5%E7%89%A9%E8%B3%87',
    kind: 'video',
    major: true,
    logo: '/logos/tvb-peacock.svg',
    image: '/images/media-tvb-1.jpg',
  },
  {
    id: 'hk01-2025',
    date: '2025-01-15',
    outlet: 'HK01 香港01',
    title: {
      en: 'HKUST sets up Low-Altitude Economy Research Center — 10-minute drone flight to High Island Reservoir',
      zhHant: '科大成立低空經濟研究中心　研無人機運送醫療物資　稱 10 分鐘可飛抵萬宜水庫',
      zhHans: '科大成立低空经济研究中心　研无人机运送医疗物资　称 10 分钟可飞抵万宜水库',
    },
    summary: {
      en: 'HK01 covers the Centre’s launch and its regulatory sandbox application: an automated drone emergency-response service delivering medical supplies from HKUST to Sai Kung’s High Island Reservoir in 10 minutes.',
      zhHant: '香港01 報道研究中心成立及「監管沙盒」申請：無人機自動化緊急應變服務由科大飛往西貢萬宜水庫運送醫療物資僅需 10 分鐘。',
      zhHans: '香港01 报道研究中心成立及「监管沙盒」申请：无人机自动化紧急应变服务由科大飞往西贡万宜水库运送医疗物资仅需 10 分钟。',
    },
    url: 'https://www.hk01.com/%E5%B0%88%E4%B8%8A%E6%95%99%E8%82%B2/1094342/%E7%A7%91%E5%A4%A7%E6%88%90%E7%AB%8B%E4%BD%8E%E7%A9%BA%E7%B6%93%E6%BF%9F%E7%A0%94%E7%A9%B6%E4%B8%AD%E5%BF%83-%E5%B7%B2%E4%BA%A4%E7%9B%A3%E7%AE%A1%E6%B2%99%E7%9B%92%E7%94%B3%E8%AB%8B-%E7%A0%94%E7%84%A1%E4%BA%BA%E6%A9%9F%E7%B7%8A%E6%80%A5%E6%95%91%E6%8F%B4',
    kind: 'article',
    major: true,
    logo: '/logos/hk01.png',
    image: '/images/media-hk01-lae-1.jpeg',
  },
  {
    id: 'lae-center-2025',
    date: '2025-01-15',
    outlet: 'HKUST News',
    title: {
      en: 'HKUST launches Low Altitude Economy Research Center',
      zhHant: '科大成立低空經濟研究中心',
      zhHans: '科大成立低空经济研究中心',
    },
    summary: {
      en: 'The official launch announcement names WU Chun-Ming as a member of the AeroRelief team and captions his live demonstration of the automated UAV emergency delivery system.',
      zhHant: '官方成立公告點名胡駿銘為 AeroRelief 研發團隊成員，並配以他現場演示自動無人機緊急運送系統的照片。',
      zhHans: '官方成立公告点名胡骏铭为 AeroRelief 研发团队成员，并配以他现场演示自动无人机紧急运送系统的照片。',
    },
    url: 'https://hkust.edu.hk/news/hkust-launches-low-altitude-economy-research-center',
    kind: 'article',
    logo: '/logos/hkust.svg',
    image: '/images/media-lae-center-1.jpg',
  },
  {
    id: 'ugc-2025',
    date: '2025-01-12',
    outlet: 'HKUST News',
    title: {
      en: 'ISD students demo hiker-rescue drone to the University Grants Committee delegation',
      zhHant: 'ISD 學生向教資會代表團演示行山救援無人機',
      zhHans: 'ISD 学生向教资会代表团演示行山救援无人机',
    },
    summary: {
      en: 'During the UGC delegation’s campus visit, Jimmy Wu’s team presents the innovative drone designed for finding lost hikers, alongside low-altitude-economy research at the Aerodynamics and Acoustics Facility.',
      zhHant: '教資會代表團到訪期間，胡駿銘團隊展示用於搜救走失行山者的創新無人機，並介紹空氣動力學與聲學實驗室的低空經濟研究。',
      zhHans: '教资会代表团到访期间，胡骏铭团队展示用于搜救走失行山者的创新无人机，并介绍空气动力学与声学实验室的低空经济研究。',
    },
    url: 'https://hkust.edu.hk/news/hkust-welcomes-university-grants-committee-delegation',
    kind: 'article',
    logo: '/logos/hkust.svg',
    image: '/images/media-ugc-delegation-1.jpg',
  },
  {
    id: 'infoday-2024',
    date: '2024-10-29',
    outlet: 'HKUST News',
    title: {
      en: 'HKUST Information Day unveils five new undergraduate programs — Jimmy Wu shares his ISD journey',
      zhHant: '科大資訊日公布五個新本科課程　胡駿銘分享跨學科學習經歷',
      zhHans: '科大资讯日公布五个新本科课程　胡骏铭分享跨学科学习经历',
    },
    summary: {
      en: 'At the press event Jimmy Wu shares his interdisciplinary learning experience at HKUST and presents the prototype his start-up developed during his studies, alongside university leadership.',
      zhHant: '胡駿銘於發布會分享在科大的跨學科學習經歷，展示其初創團隊在學期間研發的原型產品，並與校方管理層同台。',
      zhHans: '胡骏铭于发布会分享在科大的跨学科学习经历，展示其初创团队在学期间研发的原型产品，并与校方管理层同台。',
    },
    url: 'https://hkust.edu.hk/news/hkust-information-day-unveil-five-new-undergraduate-programs',
    kind: 'article',
    logo: '/logos/hkust.svg',
    image: '/images/media-infoday-1.jpg',
  },
  {
    id: 'chinachem-2024',
    date: '2024-04-17',
    outlet: 'HKUST AIS',
    title: {
      en: 'Chinachem PrimeMovership Award presentation cum project showcase 2023/24',
      zhHant: '華懋 PrimeMovership 獎學金頒授典禮暨項目展示 2023/24',
      zhHans: '华懋 PrimeMovership 奖学金颁授典礼暨项目展示 2023/24',
    },
    summary: {
      en: 'Jimmy Wu receives the Chinachem PrimeMovership Scholarship and presents his smart hotel solution to Chinachem Group executives, pictured holding his certificate alongside the Group CEO and HKUST’s Vice-President.',
      zhHant: '胡駿銘獲頒華懋 PrimeMovership 獎學金，向華懋集團管理層展示智能酒店方案，並手持證書與集團行政總裁及科大副校長合影。',
      zhHans: '胡骏铭获颁华懋 PrimeMovership 奖学金，向华懋集团管理层展示智能酒店方案，并手持证书与集团行政总裁及科大副校长合影。',
    },
    url: 'https://ais.hkust.edu.hk/whats-happening/news/chinachem-primemovership-award-presentation-cum-project-showcase-20232024',
    kind: 'article',
    logo: '/logos/chinachem.png',
    image: '/images/media-chinachem-1.jpg',
  },
  {
    id: 'artsfest-2021',
    date: '2021-12-30',
    outlet: 'HK Arts Festival 香港藝術節',
    title: {
      en: 'Six student teams reach the final of the Arts × Tech Creation Competition',
      zhHant: '「藝術 X 科技創作比賽」六隊入圍學生隊伍誕生',
      zhHans: '「艺术 X 科技创作比赛」六队入围学生队伍诞生',
    },
    summary: {
      en: 'Jimmy Wu’s cross-university team is named a tertiary-division finalist of the Hong Kong Arts Festival’s Arts × Tech competition, part of the 50th Festival’s immersive opera LAILA outreach programme.',
      zhHant: '胡駿銘的跨校隊伍入圍香港藝術節「藝術 X 科技創作比賽」大專組決賽，屬第 50 屆藝術節沉浸式歌劇《拉娜》外展教育活動之一。',
      zhHans: '胡骏铭的跨校队伍入围香港艺术节「艺术 X 科技创作比赛」大专组决赛，属第 50 届艺术节沉浸式歌剧《拉娜》外展教育活动之一。',
    },
    url: 'https://www.hk.artsfestival.org/tc/press/press-release/press-release-20211230.html',
    kind: 'article',
    logo: '/logos/hkaf.png',
  },
  {
    id: 'polyu-vr-2019',
    date: '2019-07-13',
    outlet: 'PolyU Library 理大圖書館',
    title: {
      en: 'Inter-secondary school VR contest — “The Old Summer Palace” takes 2nd runner-up',
      zhHant: '全港中學虛擬實境創作比賽——《圓明園》奪季軍',
      zhHans: '全港中学虚拟实境创作比赛——《圆明园》夺季军',
    },
    summary: {
      en: 'Jimmy Wu and his Munsang College teammates win 2nd runner-up at the first Hong Kong inter-secondary school VR creation contest with their VR story “The Old Summer Palace”, receiving the trophy at PolyU.',
      zhHant: '胡駿銘與民生書院隊友憑 VR 作品《圓明園》於首屆全港中學虛擬實境創作比賽奪得季軍，於理大頒獎典禮領取獎盃。',
      zhHans: '胡骏铭与民生书院队友凭 VR 作品《圆明园》于首届全港中学虚拟实境创作比赛夺得季军，于理大颁奖典礼领取奖杯。',
    },
    url: 'https://libguides.lb.polyu.edu.hk/i-Space/isvrc_chi',
    kind: 'article',
    logo: '/logos/polyu.png',
    image: '/images/media-polyu-ispace-1.jpg',
  },
]
